<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>_67Bet.UnitTests</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="BCrypt.Net-Next" Version="4.1.0" />
    <PackageReference Include="coverlet.collector" Version="6.0.4" />
    <PackageReference Include="FluentAssertions" Version="8.9.0" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="10.0.8" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.14.1" />
    <PackageReference Include="Moq" Version="4.20.72" />
    <PackageReference Include="xunit" Version="2.9.3" />
    <PackageReference Include="xunit.runner.visualstudio" Version="3.1.4" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Services\Wallet\67Bet.Wallet.Application\67Bet.Wallet.Application.csproj" />
    <ProjectReference Include="..\..\src\Services\Betting\67Bet.Betting.Application\67Bet.Betting.Application.csproj" />
    <ProjectReference Include="..\..\src\Services\Identity\67Bet.Identity.Application\67Bet.Identity.Application.csproj" />
    <ProjectReference Include="..\..\src\Services\CustomBet\67Bet.CustomBet.Application\67Bet.CustomBet.Application.csproj" />
    <ProjectReference Include="..\..\src\Services\Odds\67Bet.Odds.Application\67Bet.Odds.Application.csproj" />
    <ProjectReference Include="..\..\src\Services\Odds\67Bet.Odds.Domain\67Bet.Odds.Domain.csproj" />
  </ItemGroup>

</Project>